name: customer-template
namespace: neustar.citrix.adc.stylebooks
version: "3.9"
display-name: NeuStar Customer Apps StyleBooks
description: |    
    This StyleBook contains the configuration of all the apps for a customer.
schema-version: "1.0"
import-stylebooks: 
  - 
    namespace: netscaler.nitro.config
    prefix: ns
    version: "13.0"
  -
    namespace: neustar.citrix.adc.stylebooks
    prefix: neustar
    version: "3.9"
parameters:
  - 
    name: customer-name
    label: Customer
    description: Customer Name or ID that is used to differentiate a customer's config objects
    type: string
    required: true
    pattern: "^[A-Z0-9]{2}_[A-Z0-9]{2,10}$"
    key: true
    gui:
      updatable: false
  -
    name: applications
    label: List of Applications
    type: neustar::app-template-params[]
  -
    name: shared-objects
    label: Shared config
    type: neustar::customer-shared-config-template-params
    gui:
      collapse_pane: true
substitutions:
  is-none-bool(obj): if-then-else(exists($obj), true, false)
  monitorname(appname, name): $appname + "-" + $name
  sslprofilename(customername, name): $customername + "-" + $name + "-profile"
  ciphergroupname(customername, name): $customername + "-" + $name + "-ciphers"
  listname(name): replace($parameters.customer-name + "_" + $name + "_list", "-", "_")

  state:
    true: ENABLED
    false: DISABLED
  stateyn:
    true: "YES"
    false: "NO"
components:
  -
    name: cipher-comp
    type: ns::sslcipher
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: ssl-profile
    properties:
      ciphergroupname: $substitutions.ciphergroupname($parameters.customer-name, $ssl-profile.sslprofile-name)
    components:
      -
        name: cipher-bindings
        type: ns::sslcipher_sslciphersuite_binding
        repeat: $ssl-profile.ssl-ciphers
        repeat-item: cipher
        properties:
          ciphergroupname: $parent.properties.ciphergroupname
          ciphername: $cipher

  -
    name: appfw-config-comp
    type: neustar::appfw-config
    repeat: $parameters.shared-objects.waf-profiles
    repeat-item: waf-profile
    properties:
      customer-name: $parameters.customer-name
    properties-default-sources:
      - $waf-profile
  -
    name: iplist-comp
    type: ns::policydataset
    repeat: $parameters.shared-objects.list-configs
    repeat-item: list
    repeat-condition: $list.list-type == "ipv4" or $list.list-type == "ipv6"
    properties:
      name: $substitutions.listname($list.name)
      type: $list.list-type
    components:
      -
        name: iplist-bindings
        type: ns::policydataset_value_binding
        repeat: $list.values
        repeat-item: val
        properties:
          name: $parent.properties.name
          value: $val
  -
    name: cclist-comp
    type: ns::policypatset
    repeat: $parameters.shared-objects.list-configs
    repeat-item: list
    repeat-condition: $list.list-type == "countryCode"
    properties:
      name: $substitutions.listname($list.name)
    components:
      -
        name: cclist-bindings
        type: ns::policypatset_pattern_binding
        repeat: $list.values
        repeat-item: val
        properties:
          name: $parent.properties.name
          String: $val
  -
    name: responder-configs-comp
    type: neustar::responder-config-params
    repeat: $parameters.shared-objects.responder-configs
    repeat-item: responder
    properties-default-sources:
      - $responder
  -
    name: ssl-profiles-comp
    type: neustar::ssl-profile-params
    repeat: $parameters.shared-objects.ssl-profiles
    repeat-item: profile
    properties-default-sources:
      - $profile
  -
    name: applications-comp
    type: neustar::app-template
    repeat: $parameters.applications
    repeat-item: application
    properties-default-sources:
      - $application
    properties:
      customer-name: $parameters.customer-name
      shared-app-configs:
        responder-configs: $components.responder-configs-comp.properties
        ssl-profiles: $components.ssl-profiles-comp.properties



