---
name: shared-configs-for-apps-params
namespace: neustar.citrix.adc.stylebooks 
version: "3.9"
display-name: "StyleBook contains the parameters of Shared configs exposed to Apps"
description: "StyleBook contains the parameters of Shared configs exposed to Apps"
schema-version: "1.0"
private: true
import-stylebooks:
  - 
    namespace: com.citrix.adc.commontypes
    prefix: cmtypes
    version: "1.0"
 
parameters:
  -
    name: shared-app-configs
    type: object
    parameters:
      -
        name: responder-configs
        type: object[]
        parameters:
          -
            name: name
            type: string
            required: true
          - 
            name: rate-limiter
            type: object
            parameters:
            -
              name: rl-field
              type: string[]
            -
              name: rl-count
              type: number
            - 
              name: rl-time
              type: number
          -
            name: action
            type: string
          -
            name: expression
            type: string
          -
            name: target
            type: string
      -
        name: ssl-profiles
        type: object[]
        parameters:
          -
            name: sslprofile-name
            type: string

          -
            name: ssl-protocols
            type: object
            parameters:
              -
                name: ssl3
                type: boolean
              -
                name: tls1
                type: boolean
              -
                name: tls11
                type: boolean
              -
                name: tls12
                type: boolean
              -
                name: tls13
                type: boolean
          - 
            name: hsts
            type: object
            parameters:
              - 
                name: maxage
                type: number
              -
                name: preload
                type: boolean
              -
                name: includesubs
                type: boolean
          -
            name: sni
            type: boolean
          -
            name: backend-sni
            type: object
            parameters:
              - 
                name: common-name
                type: string
          -
            name: ssl-ciphers
            type: string[]
          -
            name: backend-ciphers
            type: boolean


